#!/usr/bin/env bash
# Round-2 preflight: construct + forward + train_on_batch each variant via --sanity.
set -uo pipefail
CODE=/data/BNJetTag
fail=0
echo "=== BitNet round-2 preflight $(date) ==="
echo "--- r2-small-lr05 (recipe[BN_LR=0.00005] arch[default-arch]) ---"
if env CUDA_VISIBLE_DEVICES=-1 BN_D_MODEL=64 BN_N_HEADS=8 BN_N_LAYERS=3 BN_FFN_DIM=256 BN_LR=0.00005 python -u "$CODE/qkerasModel.py" --sanity > /tmp/pf2_small-lr05.log 2>&1 && grep -q "Total trainable parameters" /tmp/pf2_small-lr05.log && ! grep -qE "Traceback|Exception" /tmp/pf2_small-lr05.log; then p=$(grep "Total trainable parameters" /tmp/pf2_small-lr05.log | tail -1); echo "  PASS small-lr05  ($p)"; else echo "  FAIL small-lr05"; tail -30 /tmp/pf2_small-lr05.log; fail=1; fi
echo "--- r2-small-lr075 (recipe[BN_LR=0.000075] arch[default-arch]) ---"
if env CUDA_VISIBLE_DEVICES=-1 BN_D_MODEL=64 BN_N_HEADS=8 BN_N_LAYERS=3 BN_FFN_DIM=256 BN_LR=0.000075 python -u "$CODE/qkerasModel.py" --sanity > /tmp/pf2_small-lr075.log 2>&1 && grep -q "Total trainable parameters" /tmp/pf2_small-lr075.log && ! grep -qE "Traceback|Exception" /tmp/pf2_small-lr075.log; then p=$(grep "Total trainable parameters" /tmp/pf2_small-lr075.log | tail -1); echo "  PASS small-lr075  ($p)"; else echo "  FAIL small-lr075"; tail -30 /tmp/pf2_small-lr075.log; fail=1; fi
echo "--- r2-small-lr10 (recipe[BN_LR=0.0001] arch[default-arch]) ---"
if env CUDA_VISIBLE_DEVICES=-1 BN_D_MODEL=64 BN_N_HEADS=8 BN_N_LAYERS=3 BN_FFN_DIM=256 BN_LR=0.0001 python -u "$CODE/qkerasModel.py" --sanity > /tmp/pf2_small-lr10.log 2>&1 && grep -q "Total trainable parameters" /tmp/pf2_small-lr10.log && ! grep -qE "Traceback|Exception" /tmp/pf2_small-lr10.log; then p=$(grep "Total trainable parameters" /tmp/pf2_small-lr10.log | tail -1); echo "  PASS small-lr10  ($p)"; else echo "  FAIL small-lr10"; tail -30 /tmp/pf2_small-lr10.log; fail=1; fi
echo "--- r2-small-lr10-warm3 (recipe[BN_LR=0.0001,BN_WARMUP_EPOCHS=3] arch[default-arch]) ---"
if env CUDA_VISIBLE_DEVICES=-1 BN_D_MODEL=64 BN_N_HEADS=8 BN_N_LAYERS=3 BN_FFN_DIM=256 BN_LR=0.0001 BN_WARMUP_EPOCHS=3 python -u "$CODE/qkerasModel.py" --sanity > /tmp/pf2_small-lr10-warm3.log 2>&1 && grep -q "Total trainable parameters" /tmp/pf2_small-lr10-warm3.log && ! grep -qE "Traceback|Exception" /tmp/pf2_small-lr10-warm3.log; then p=$(grep "Total trainable parameters" /tmp/pf2_small-lr10-warm3.log | tail -1); echo "  PASS small-lr10-warm3  ($p)"; else echo "  FAIL small-lr10-warm3"; tail -30 /tmp/pf2_small-lr10-warm3.log; fail=1; fi
echo "--- r2-combo-small (recipe[lr15] arch[BN_POOL=cls,BN_FFN_ACT=gelu,BN_POS_ENC=none]) ---"
if env CUDA_VISIBLE_DEVICES=-1 BN_D_MODEL=64 BN_N_HEADS=8 BN_N_LAYERS=3 BN_FFN_DIM=256 BN_POOL=cls BN_FFN_ACT=gelu BN_POS_ENC=none python -u "$CODE/qkerasModel.py" --sanity > /tmp/pf2_combo-small.log 2>&1 && grep -q "Total trainable parameters" /tmp/pf2_combo-small.log && ! grep -qE "Traceback|Exception" /tmp/pf2_combo-small.log; then p=$(grep "Total trainable parameters" /tmp/pf2_combo-small.log | tail -1); echo "  PASS combo-small  ($p)"; else echo "  FAIL combo-small"; tail -30 /tmp/pf2_combo-small.log; fail=1; fi
echo "--- r2-combo-medium (recipe[lr15] arch[BN_POOL=cls,BN_FFN_ACT=gelu,BN_POS_ENC=none]) ---"
if env CUDA_VISIBLE_DEVICES=-1 BN_D_MODEL=128 BN_N_HEADS=8 BN_N_LAYERS=4 BN_FFN_DIM=512 BN_POOL=cls BN_FFN_ACT=gelu BN_POS_ENC=none python -u "$CODE/qkerasModel.py" --sanity > /tmp/pf2_combo-medium.log 2>&1 && grep -q "Total trainable parameters" /tmp/pf2_combo-medium.log && ! grep -qE "Traceback|Exception" /tmp/pf2_combo-medium.log; then p=$(grep "Total trainable parameters" /tmp/pf2_combo-medium.log | tail -1); echo "  PASS combo-medium  ($p)"; else echo "  FAIL combo-medium"; tail -30 /tmp/pf2_combo-medium.log; fail=1; fi
echo "--- r2-small-s1 (recipe[BN_SEED=1] arch[default-arch]) ---"
if env CUDA_VISIBLE_DEVICES=-1 BN_D_MODEL=64 BN_N_HEADS=8 BN_N_LAYERS=3 BN_FFN_DIM=256 BN_SEED=1 python -u "$CODE/qkerasModel.py" --sanity > /tmp/pf2_small-s1.log 2>&1 && grep -q "Total trainable parameters" /tmp/pf2_small-s1.log && ! grep -qE "Traceback|Exception" /tmp/pf2_small-s1.log; then p=$(grep "Total trainable parameters" /tmp/pf2_small-s1.log | tail -1); echo "  PASS small-s1  ($p)"; else echo "  FAIL small-s1"; tail -30 /tmp/pf2_small-s1.log; fail=1; fi
echo "--- r2-small-s2 (recipe[BN_SEED=2] arch[default-arch]) ---"
if env CUDA_VISIBLE_DEVICES=-1 BN_D_MODEL=64 BN_N_HEADS=8 BN_N_LAYERS=3 BN_FFN_DIM=256 BN_SEED=2 python -u "$CODE/qkerasModel.py" --sanity > /tmp/pf2_small-s2.log 2>&1 && grep -q "Total trainable parameters" /tmp/pf2_small-s2.log && ! grep -qE "Traceback|Exception" /tmp/pf2_small-s2.log; then p=$(grep "Total trainable parameters" /tmp/pf2_small-s2.log | tail -1); echo "  PASS small-s2  ($p)"; else echo "  FAIL small-s2"; tail -30 /tmp/pf2_small-s2.log; fail=1; fi
echo "--- r2-clspool-s1 (recipe[BN_SEED=1] arch[BN_POOL=cls]) ---"
if env CUDA_VISIBLE_DEVICES=-1 BN_D_MODEL=64 BN_N_HEADS=8 BN_N_LAYERS=3 BN_FFN_DIM=256 BN_SEED=1 BN_POOL=cls python -u "$CODE/qkerasModel.py" --sanity > /tmp/pf2_clspool-s1.log 2>&1 && grep -q "Total trainable parameters" /tmp/pf2_clspool-s1.log && ! grep -qE "Traceback|Exception" /tmp/pf2_clspool-s1.log; then p=$(grep "Total trainable parameters" /tmp/pf2_clspool-s1.log | tail -1); echo "  PASS clspool-s1  ($p)"; else echo "  FAIL clspool-s1"; tail -30 /tmp/pf2_clspool-s1.log; fail=1; fi
echo "--- r2-clspool-s2 (recipe[BN_SEED=2] arch[BN_POOL=cls]) ---"
if env CUDA_VISIBLE_DEVICES=-1 BN_D_MODEL=64 BN_N_HEADS=8 BN_N_LAYERS=3 BN_FFN_DIM=256 BN_SEED=2 BN_POOL=cls python -u "$CODE/qkerasModel.py" --sanity > /tmp/pf2_clspool-s2.log 2>&1 && grep -q "Total trainable parameters" /tmp/pf2_clspool-s2.log && ! grep -qE "Traceback|Exception" /tmp/pf2_clspool-s2.log; then p=$(grep "Total trainable parameters" /tmp/pf2_clspool-s2.log | tail -1); echo "  PASS clspool-s2  ($p)"; else echo "  FAIL clspool-s2"; tail -30 /tmp/pf2_clspool-s2.log; fail=1; fi
if [ "$fail" = 0 ]; then echo "PREFLIGHT_ALL_PASS"; else echo "PREFLIGHT_HAD_FAILURES"; fi
